version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/GasMileageTracking/GasMileageTracking.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet lambda package-ci -ot serverless.template
artifacts:
  files:
    - src/GasMileageTracking/build_output/**/*
    - scripts/**/*
    - serverless.template