version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet --version
      - dotnet restore src/GasMileageTracking/GasMileageTracking.csproj
  build:
    commands:
      - echo Build started on `date`
      - cd src/GasMileageTracking
      - dotnet lambda package-ci -ot ../../serverless.template --s3-bucket ryanmeriaamaawstest
artifacts:
  files:
    - serverless.template
  discard-paths: yes